// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DaterangepickerController from "./daterangepicker_controller"
application.register("daterangepicker", DaterangepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotiController from "./noti_controller"
application.register("noti", NotiController)

import TestController from "./test_controller"
application.register("test", TestController)
