require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/benefits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Benefit. As you add validations to Benefit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Benefit.create! valid_attributes
      get benefits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      benefit = Benefit.create! valid_attributes
      get benefit_url(benefit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_benefit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      benefit = Benefit.create! valid_attributes
      get edit_benefit_url(benefit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Benefit" do
        expect {
          post benefits_url, params: { benefit: valid_attributes }
        }.to change(Benefit, :count).by(1)
      end

      it "redirects to the created benefit" do
        post benefits_url, params: { benefit: valid_attributes }
        expect(response).to redirect_to(benefit_url(Benefit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Benefit" do
        expect {
          post benefits_url, params: { benefit: invalid_attributes }
        }.to change(Benefit, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post benefits_url, params: { benefit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested benefit" do
        benefit = Benefit.create! valid_attributes
        patch benefit_url(benefit), params: { benefit: new_attributes }
        benefit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the benefit" do
        benefit = Benefit.create! valid_attributes
        patch benefit_url(benefit), params: { benefit: new_attributes }
        benefit.reload
        expect(response).to redirect_to(benefit_url(benefit))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        benefit = Benefit.create! valid_attributes
        patch benefit_url(benefit), params: { benefit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested benefit" do
      benefit = Benefit.create! valid_attributes
      expect {
        delete benefit_url(benefit)
      }.to change(Benefit, :count).by(-1)
    end

    it "redirects to the benefits list" do
      benefit = Benefit.create! valid_attributes
      delete benefit_url(benefit)
      expect(response).to redirect_to(benefits_url)
    end
  end
end
