require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/brand_categories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BrandCategory. As you add validations to BrandCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BrandCategory.create! valid_attributes
      get brand_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      brand_category = BrandCategory.create! valid_attributes
      get brand_category_url(brand_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_brand_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      brand_category = BrandCategory.create! valid_attributes
      get edit_brand_category_url(brand_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BrandCategory" do
        expect {
          post brand_categories_url, params: { brand_category: valid_attributes }
        }.to change(BrandCategory, :count).by(1)
      end

      it "redirects to the created brand_category" do
        post brand_categories_url, params: { brand_category: valid_attributes }
        expect(response).to redirect_to(brand_category_url(BrandCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BrandCategory" do
        expect {
          post brand_categories_url, params: { brand_category: invalid_attributes }
        }.to change(BrandCategory, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post brand_categories_url, params: { brand_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested brand_category" do
        brand_category = BrandCategory.create! valid_attributes
        patch brand_category_url(brand_category), params: { brand_category: new_attributes }
        brand_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the brand_category" do
        brand_category = BrandCategory.create! valid_attributes
        patch brand_category_url(brand_category), params: { brand_category: new_attributes }
        brand_category.reload
        expect(response).to redirect_to(brand_category_url(brand_category))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        brand_category = BrandCategory.create! valid_attributes
        patch brand_category_url(brand_category), params: { brand_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested brand_category" do
      brand_category = BrandCategory.create! valid_attributes
      expect {
        delete brand_category_url(brand_category)
      }.to change(BrandCategory, :count).by(-1)
    end

    it "redirects to the brand_categories list" do
      brand_category = BrandCategory.create! valid_attributes
      delete brand_category_url(brand_category)
      expect(response).to redirect_to(brand_categories_url)
    end
  end
end
