require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/brand_partners", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BrandPartner. As you add validations to BrandPartner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BrandPartner.create! valid_attributes
      get brand_partners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      brand_partner = BrandPartner.create! valid_attributes
      get brand_partner_url(brand_partner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_brand_partner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      brand_partner = BrandPartner.create! valid_attributes
      get edit_brand_partner_url(brand_partner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BrandPartner" do
        expect {
          post brand_partners_url, params: { brand_partner: valid_attributes }
        }.to change(BrandPartner, :count).by(1)
      end

      it "redirects to the created brand_partner" do
        post brand_partners_url, params: { brand_partner: valid_attributes }
        expect(response).to redirect_to(brand_partner_url(BrandPartner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BrandPartner" do
        expect {
          post brand_partners_url, params: { brand_partner: invalid_attributes }
        }.to change(BrandPartner, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post brand_partners_url, params: { brand_partner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested brand_partner" do
        brand_partner = BrandPartner.create! valid_attributes
        patch brand_partner_url(brand_partner), params: { brand_partner: new_attributes }
        brand_partner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the brand_partner" do
        brand_partner = BrandPartner.create! valid_attributes
        patch brand_partner_url(brand_partner), params: { brand_partner: new_attributes }
        brand_partner.reload
        expect(response).to redirect_to(brand_partner_url(brand_partner))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        brand_partner = BrandPartner.create! valid_attributes
        patch brand_partner_url(brand_partner), params: { brand_partner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested brand_partner" do
      brand_partner = BrandPartner.create! valid_attributes
      expect {
        delete brand_partner_url(brand_partner)
      }.to change(BrandPartner, :count).by(-1)
    end

    it "redirects to the brand_partners list" do
      brand_partner = BrandPartner.create! valid_attributes
      delete brand_partner_url(brand_partner)
      expect(response).to redirect_to(brand_partners_url)
    end
  end
end
